### ISSUE TITLE
How to add a eclipse plugin into monkeytalk ide?

### ISSUE THREAD

**Issue by qch123** [alexnauda/monkeytalk#1]
I download a xmlbuddy plugin and put it into your monkeytalk ide plugins directory,but it does not work。 could you tall me how to fix this,thanks

**Comment by alexnauda** [comment]
I'm not the author or maintainer of monkeytalk. This repo is a fork of the codebase downloaded from https://www.cloudmonkeymobile.com/monkeytalk that contains a minor fix that I needed to make it work for me. Please contact the original developer.

**Comment by qch123** [comment]
could you tall me how to download the latest monkeytalk source code?

**Comment by qch123** [comment]
I have found the latest source code,thank you.

**Comment by xiaobeiying** [comment]
@qch123  Where did you found? Could you share with us, tks.
